name: Azure Deploy

on:
  push:
    branches:
      - main

env:
    AZURE_FUNCTIONS_PACKAGE_PATH: './src/'
    DOTENT_VERSION : '8.0.x'


jobs:
    build:
        runs-on: windows-latest
        permissions:
            packages: write
            contents: read
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ env.DOTENT_VERSION }}

            - name: 'Resolve Project Dependencies Using Dotnet'
              shell: pwsh
              run: |
                pushd './${{ env.AZURE_FUNCTIONS_PACKAGE_PATH }}'
                dotnet build --configuration Release --output ./output
                popd

            - name: Azure Login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            - name: Azure Functions Deploy
              uses: Azure/functions-action@v1
              id: fa
              with:
                app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
                slot-name: 'production'
                package: '${{ env.AZURE_FUNCTIONS_PACKAGE_PATH }}/output'




